server:
  port: 8585
  http2:
    enabled: true

spring:
  application:
    name: PxelSoftware
  datasource:
    url: jdbc:postgresql://localhost:5432/HibernatePractic
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: pixel
        show_sql: true
        format_sql: true
        hbm2ddl:
          import_files: /import.sql
          auto: create
  quartz:
    job-store-type: jdbc #Database Mode
    jdbc:
      initialize-schema: never #Do not initialize table structure
    properties:
      org:
        quartz:
         jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate #We only make database-specific proxies for databases
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            dataSource: quartzDataSource
            tablePrefix: QRTZ_

logging:
  level:
      root: INFO
      org.springframework.jdbc.core: TRACE
      org.springframework.security: TRACE

jwt:
  access-token-key: '{"kty":"oct","k":"404491d134b23069cd800106d3e2edd63996def57f8f1530e4e7bc8dbdf80fb9"}'
  refresh-token-key: '{"kty":"oct","k":"404491d134b23069cd800106d3e2edd63996def57f8f1530e4e7bc8dbdf80fb9"}'
  request-path: "/jwt/tokens"
  refresh-path: "/jwt/refresh"
  logout-path: "/jwt/logout"
  duration-refresh-interval-hours: 2
  duration-access-interval-min: 10


management:
  endpoints:
    web:
      exposure:
        include: quartz
      quartz:
        enabled: true


max-deposit-percent: 210


