server:
  port: 8585
  http2:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: quartz
      quartz:
        enabled: true

spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            isClustered: true
            clusterCheckinInterval: 20000
            misfireThreshold: 60000
            useProperties: true
          scheduler:
            instanceId: AUTO
            instanceName: quartz-demo
          threadPool:
            threadCount: 10
            threadPriority: 5
            class: org.quartz.simpl.SimpleThreadPool

  application:
    name: PxelSoftware
  datasource:
    name: quartzDataSource
    url: jdbc:postgresql://localhost:5432/HibernatePractic?currentSchema=pixel
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: pixel
        show_sql: true
        format_sql: true
        hbm2ddl:
          import_files: /import.sql
          auto: validate
          #auto: create


logging:
  level:
      root: INFO
      org.springframework.jdbc.core: TRACE
      org.springframework.security: TRACE

jwt:
  access-token-key: '{"kty":"oct","k":"404491d134b23069cd800106d3e2edd63996def57f8f1530e4e7bc8dbdf80fb9"}'
  refresh-token-key: '{"kty":"oct","k":"404491d134b23069cd800106d3e2edd63996def57f8f1530e4e7bc8dbdf80fb9"}'
  request-path: "/jwt/tokens"
  refresh-path: "/jwt/refresh"
  logout-path: "/jwt/logout"
  duration-refresh-interval-hours: 2
  duration-access-interval-min: 10

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"

app:
  max-deposit-percent: 210
  start-update-deposit-milliseconds: 45
  interval-update-deposit-milliseconds: 30000
  start-update-state-deposit-milliseconds: 45
  interval-update-state-deposit-min: 1
  cron: "0 0/1 * * * ? *"


